### ISSUE TITLE
[KIALI-1497] Create liveliness and ready probes for Kiali pod 

### ISSUE THREAD

**Issue by vnugent** [kiali/hacktoberfest18#9]
Create liveliness and ready probes for Kiali pod
Health probes documentation: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

Kiali pod definition:
- Kubernetes: https://github.com/kiali/kiali/blob/master/deploy/kubernetes/kiali.yaml
- OpenShift: https://github.com/kiali/kiali/blob/master/deploy/openshift/kiali.yaml

Suggestions:
For both readiness and liveness check use the built-in `httpGet` to access `<kiali url>/api/status` .  For example:

```
    livenessProbe:
      httpGet:
        path: /api/status
        port: 20001
      initialDelaySeconds: 3
      periodSeconds: 3
```
